In [9]:
import pandas as pd
from UnivariateFile import UnivariateClass

In [2]:
dataset=pd.read_csv("Preprocessed_Data_Cryptos.csv")
dataset.head()

,Year,Month,Day,Hour,Minute,Volume,Open,High,Low,Close,Price_Prediction
0,2012,1,1,10,1,0.0,4.58,4.58,4.58,4.58,Neutral
1,2012,1,1,10,2,0.0,4.58,4.58,4.58,4.58,Neutral
2,2012,1,1,10,3,0.0,4.58,4.58,4.58,4.58,Neutral
3,2012,1,1,10,4,0.0,4.58,4.58,4.58,4.58,Neutral
4,2012,1,1,10,5,0.0,4.58,4.58,4.58,4.58,Neutral

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 11 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   Year              1048575 non-null  int64
 1   Month             1048575 non-null  int64
 2   Day               1048575 non-null  int64
 3   Hour              1048575 non-null  int64
 4   Minute            1048575 non-null  int64
 5   Volume            1048575 non-null  float64
 6   Open              1048575 non-null  float64
 7   High              1048575 non-null  float64
 8   Low               1048575 non-null  float64
 9   Close             1048575 non-null  float64
 10  Price_Prediction  1048575 non-null  object
dtypes: float64(5), int64(5), object(1)
memory usage: 88.0+ MB

In [5]:
for columnName in dataset.columns:
    print(columnName)

Year
Month
Day
Hour
Minute
Volume
Open
High
Low
Close
Price_Prediction

In [10]:
quan,qual = UnivariateClass.quanQual(dataset)
quan, qual

(['Year',
  'Month',
  'Day',
  'Hour',
  'Minute',
  'Volume',
  'Open',
  'High',
  'Low',
  'Close'],
 ['Price_Prediction'])

#Central Tendency

In [11]:
dataset.describe() #Here, Median, Mode are Missing. So we need to create our own Function

,Year,Month,Day,Hour,Minute,Volume,Open,High,Low,Close
count,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06
mean,2.012498e+03,6.504896e+00,1.569923e+01,1.150004e+01,2.949969e+01,5.319984e+00,9.548771e+01,9.560149e+01,9.535922e+01,9.548245e+01
std,4.999960e-01,3.439280e+00,8.774190e+00,6.921376e+00,1.731819e+01,2.854536e+01,1.897826e+02,1.901088e+02,1.894213e+02,1.897759e+02
min,2.012000e+03,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.800000e+00,3.800000e+00,3.800000e+00,3.800000e+00
25%,2.012000e+03,4.000000e+00,8.000000e+00,6.000000e+00,1.400000e+01,0.000000e+00,6.800000e+00,6.800000e+00,6.800000e+00,6.800000e+00
50%,2.012000e+03,7.000000e+00,1.600000e+01,1.200000e+01,2.900000e+01,0.000000e+00,1.334000e+01,1.334000e+01,1.334000e+01,1.334000e+01
75%,2.013000e+03,9.000000e+00,2.300000e+01,1.700000e+01,4.400000e+01,9.003318e-01,1.101300e+02,1.102200e+02,1.100100e+02,1.101100e+02
max,2.013000e+03,1.200000e+01,3.100000e+01,2.300000e+01,5.900000e+01,2.958478e+03,1.163000e+03,1.163000e+03,1.162990e+03,1.163000e+03

In [ ]:
descriptive = pd.DataFrame() #The Keyword - DataFrame Will create a Table
descriptive #The Output is Just a _ Because we did not declare any Index and Column Name(s)

In [ ]:
descriptive = pd.DataFrame(index=["Mean","Median","Mode"],columns=quan)
descriptive

In [ ]:
#To Automate the "Mean","Median","Mode" to be filled in Table automatically

descriptive = pd.DataFrame(index=["Mean","Median","Mode"],columns=quan)

for columnName in quan:
    descriptive[columnName]["Mean"] = dataset[columnName].mean()
    descriptive[columnName]["Median"] = dataset[columnName].median()
    descriptive[columnName]["Mode"] = dataset[columnName].mode()[0]

descriptive

### Percentile

In [ ]:
import numpy as np

In [ ]:
#To Verify any Levels (25%, 50% etc) of Percentile
np.percentile(dataset["open"],25)

In [ ]:
#To Automate the "Mean","Median","Mode" and "Level of Percentile" to be filled in Table automatically

descriptive = pd.DataFrame(index=["Mean","Median","Mode","Q1:25%","Q2:50%","Q3:75%","99%","Q4:100%"],columns=quan)

for columnName in quan:
    descriptive[columnName]["Mean"] = dataset[columnName].mean()
    descriptive[columnName]["Median"] = dataset[columnName].median()
    descriptive[columnName]["Mode"] = dataset[columnName].mode()[0]
    descriptive[columnName]["Q1:25%"] = dataset.describe()[columnName]["25%"]
    descriptive[columnName]["Q2:50%"] = dataset.describe()[columnName]["50%"]
    descriptive[columnName]["Q3:75%"] = dataset.describe()[columnName]["75%"]
    descriptive[columnName]["99%"] = np.percentile(dataset[columnName],99)
    descriptive[columnName]["Q4:100%"] = dataset.describe()[columnName]["max"]

descriptive

In [ ]:
"""
Dataset (With Outliers)
To Automate the "Mean","Median","Mode" and "Level of Percentile"("Q1:25%","Q2:50%","Q3:75%","99%","Q4:100%"),
"IQR","1.5_rule","LesserOutlier","GreaterOutlier","MinValue","MaxValue" to be filled in Table automatically
"""

descriptive = pd.DataFrame(index=["Mean","Median","Mode","Q1:25%","Q2:50%","Q3:75%","99%","Q4:100%","IQR","1.5_rule",
                                  "LesserOutlier","GreaterOutlier","MinValue","MaxValue"],columns=quan)

for columnName in quan:
    descriptive[columnName]["Mean"] = dataset[columnName].mean()
    descriptive[columnName]["Median"] = dataset[columnName].median()
    descriptive[columnName]["Mode"] = dataset[columnName].mode()[0]
    descriptive[columnName]["Q1:25%"] = dataset.describe()[columnName]["25%"]
    descriptive[columnName]["Q2:50%"] = dataset.describe()[columnName]["50%"]
    descriptive[columnName]["Q3:75%"] = dataset.describe()[columnName]["75%"]
    descriptive[columnName]["99%"] = np.percentile(dataset[columnName],99)
    descriptive[columnName]["Q4:100%"] = dataset.describe()[columnName]["max"]
    
    descriptive[columnName]["IQR"] = descriptive[columnName]["Q3:75%"] - descriptive[columnName]["Q1:25%"]
    descriptive[columnName]["1.5_rule"] = 1.5 * descriptive[columnName]["IQR"]
    descriptive[columnName]["LesserOutlier"] = descriptive[columnName]["Q1:25%"] - descriptive[columnName]["1.5_rule"]
    descriptive[columnName]["GreaterOutlier"] = descriptive[columnName]["Q3:75%"] + descriptive[columnName]["1.5_rule"]
    descriptive[columnName]["MinValue"] = dataset[columnName].min()
    descriptive[columnName]["MaxValue"] = dataset[columnName].max()

descriptive

In [ ]:
#To Findout Presence of Outliers in Column(s) 

LesserOutlierColumnName=[]
GreaterOutlierColumnName=[]

for checkOutlierColumnName in quan :
    if (descriptive[checkOutlierColumnName]["MinValue"] < descriptive[checkOutlierColumnName]["LesserOutlier"]):
        LesserOutlierColumnName.append(checkOutlierColumnName)        
    if (descriptive[checkOutlierColumnName]["MaxValue"] > descriptive[checkOutlierColumnName]["GreaterOutlier"]):
        GreaterOutlierColumnName.append(checkOutlierColumnName)
        
print(f"{LesserOutlierColumnName}\n{GreaterOutlierColumnName}")

In [ ]:
#Creating a Function - OutlierColumnNames(with Parameter) To Automate by Findingout the Presence of Outliers in Column(s) 

def OutlierColumnNames(quan):

    LesserOutlierColumnName=[]
    GreaterOutlierColumnName=[]

    for checkOutlierColumnName in quan :
        if (descriptive[checkOutlierColumnName]["MinValue"] < descriptive[checkOutlierColumnName]["LesserOutlier"]):
            LesserOutlierColumnName.append(checkOutlierColumnName)        
        if (descriptive[checkOutlierColumnName]["MaxValue"] > descriptive[checkOutlierColumnName]["GreaterOutlier"]):
            GreaterOutlierColumnName.append(checkOutlierColumnName)

    return (f"{LesserOutlierColumnName}\n{GreaterOutlierColumnName}")

In [ ]:
OutlierColumnNames(quan)

In [ ]:
#To Replace the Existing Outlier in Dataset

LesserOutlierColumnName=[]
GreaterOutlierColumnName=[]

for columnName in LesserOutlierColumnName:
    dataset[columnName][dataset[columnName] < descriptive[checkOutlierColumnName]["LesserOutlier"]] = descriptive[checkOutlierColumnName]["LesserOutlier"]
for columnName in GreaterOutlierColumnName:
    dataset[columnName][dataset[columnName] > descriptive[checkOutlierColumnName]["GreaterOutlier"]] = descriptive[checkOutlierColumnName]["GreaterOutlier"]

In [ ]:
"""Creating a Function - ReplaceOutliers (with Parameter) To Automate by Replacing the Existing Outlier in Dataset"""

def ReplaceOutliers(LesserOutlierColumnName,dataset,checkOutlierColumnName,GreaterOutlierColumnName):
    for columnName in LesserOutlierColumnName:
        dataset[columnName][dataset[columnName] < descriptive[checkOutlierColumnName]["LesserOutlier"]] = descriptive[checkOutlierColumnName]["LesserOutlier"]
    for columnName in GreaterOutlierColumnName:
        dataset[columnName][dataset[columnName] > descriptive[checkOutlierColumnName]["GreaterOutlier"]] = descriptive[checkOutlierColumnName]["GreaterOutlier"]

In [ ]:
ReplaceOutliers(LesserOutlierColumnName,dataset,checkOutlierColumnName,GreaterOutlierColumnName)

In [ ]:
""" To Cross check the Updated Dataset (Without Outliers) is Updated or Not by Univariating
To Automate the "Mean","Median","Mode" and "Level of Percentile"("Q1:25%","Q2:50%","Q3:75%","99%","Q4:100%"),
"IQR","1.5_rule","LesserOutlier","GreaterOutlier","MinValue","MaxValue" to be filled in Table automatically
"""

descriptive = pd.DataFrame(index=["Mean","Median","Mode","Q1:25%","Q2:50%","Q3:75%","99%","Q4:100%","IQR","1.5_rule",
                                  "LesserOutlier","GreaterOutlier","MinValue","MaxValue"],columns=quan)

for columnName in quan:
    descriptive[columnName]["Mean"] = dataset[columnName].mean()
    descriptive[columnName]["Median"] = dataset[columnName].median()
    descriptive[columnName]["Mode"] = dataset[columnName].mode()[0]
    descriptive[columnName]["Q1:25%"] = dataset.describe()[columnName]["25%"]
    descriptive[columnName]["Q2:50%"] = dataset.describe()[columnName]["50%"]
    descriptive[columnName]["Q3:75%"] = dataset.describe()[columnName]["75%"]
    descriptive[columnName]["99%"] = np.percentile(dataset[columnName],99)
    descriptive[columnName]["Q4:100%"] = dataset.describe()[columnName]["max"]
    
    descriptive[columnName]["IQR"] = descriptive[columnName]["Q3:75%"] - descriptive[columnName]["Q1:25%"]
    descriptive[columnName]["1.5_rule"] = 1.5 * descriptive[columnName]["IQR"]
    descriptive[columnName]["LesserOutlier"] = descriptive[columnName]["Q1:25%"] - descriptive[columnName]["1.5_rule"]
    descriptive[columnName]["GreaterOutlier"] = descriptive[columnName]["Q3:75%"] + descriptive[columnName]["1.5_rule"]
    descriptive[columnName]["MinValue"] = dataset[columnName].min()
    descriptive[columnName]["MaxValue"] = dataset[columnName].max()

descriptive

In [ ]:
"""
To Cross check the Updated Dataset (Without Outliers) is Updated or Not
To Findout Presence of Outliers in Column(s) 
"""

LesserOutlierColumnName=[]
GreaterOutlierColumnName=[]

for checkOutlierColumnName in quan :
    if (descriptive[checkOutlierColumnName]["MinValue"] < descriptive[checkOutlierColumnName]["LesserOutlier"]):
        LesserOutlierColumnName.append(checkOutlierColumnName)        
    if (descriptive[checkOutlierColumnName]["MaxValue"] > descriptive[checkOutlierColumnName]["GreaterOutlier"]):
        GreaterOutlierColumnName.append(checkOutlierColumnName)
        
print(f"{LesserOutlierColumnName}\n{GreaterOutlierColumnName}")

In [ ]:
"""Creating a Function To Automate the "Mean","Median","Mode" and "Level of Percentile"("Q1:25%","Q2:50%","Q3:75%","99%","Q4:100%"),
"IQR","1.5_rule","LesserOutlier","GreaterOutlier","MinValue","MaxValue", "Skewness", "Kurtosis", "Variance", "StdDeviation" 
to be filled in Table automatically """

def Univariate(dataset,quan):
    descriptive = pd.DataFrame(index=["Mean","Median","Mode","Q1:25%","Q2:50%","Q3:75%","99%","Q4:100%","IQR","1.5_rule",
                        "LesserOutlier","GreaterOutlier","MinValue","MaxValue","Skewness","Kurtosis",
                                      "Variance","StdDeviation"],columns=quan)

    for columnName in quan:
            descriptive[columnName]["Mean"] = dataset[columnName].mean()
            descriptive[columnName]["Median"] = dataset[columnName].median()
            descriptive[columnName]["Mode"] = dataset[columnName].mode()[0]
            descriptive[columnName]["Q1:25%"] = dataset.describe()[columnName]["25%"]
            descriptive[columnName]["Q2:50%"] = dataset.describe()[columnName]["50%"]
            descriptive[columnName]["Q3:75%"] = dataset.describe()[columnName]["75%"]
            descriptive[columnName]["99%"] = np.percentile(dataset[columnName],99)
            descriptive[columnName]["Q4:100%"] = dataset.describe()[columnName]["max"]

            descriptive[columnName]["IQR"] = descriptive[columnName]["Q3:75%"] - descriptive[columnName]["Q1:25%"]
            descriptive[columnName]["1.5_rule"] = 1.5 * descriptive[columnName]["IQR"]
            descriptive[columnName]["LesserOutlier"] = descriptive[columnName]["Q1:25%"] - descriptive[columnName]["1.5_rule"]
            descriptive[columnName]["GreaterOutlier"] = descriptive[columnName]["Q3:75%"] + descriptive[columnName]["1.5_rule"]
            descriptive[columnName]["MinValue"] = dataset[columnName].min()
            descriptive[columnName]["MaxValue"] = dataset[columnName].max()
            
            descriptive[columnName]["Skewness"] = dataset[columnName].skew()
            descriptive[columnName]["Kurtosis"] = dataset[columnName].kurtosis()
            
            descriptive[columnName]["Variance"] = dataset[columnName].var()
            descriptive[columnName]["StdDeviation"] = dataset[columnName].std()
        
    return descriptive

In [ ]:
#1. Import the class from the file
from UnivariateFile import UnivariateClass

In [ ]:
#2. Create an object of the class
obj = UnivariateClass()

In [ ]:
#3. Call the method (function inside class)
Univariate(dataset, quan)

### Frequency

In [ ]:
"""
Purpose: It gives Both Unique Values and Repeatation of Each Unique Values
"""
dataset["open"].value_counts()

In [ ]:
"""
Purpose: It gives Only Unique Values
"""
dataset["open"].value_counts().index

In [ ]:
"""
Purpose: It gives Only the Repeatation (Count) of Each Unique Values
"""
dataset["open"].value_counts().values

In [ ]:
"""
Purpose: It gives Only Sorted Unique Values
"""
dataset["open"].value_counts().sort_index

In [ ]:
"""
Purpose: It gives Only Sorted Repeatation (Sorted Count) of Each Unique Values
"""
dataset["open"].value_counts().sort_values

In [ ]:
"""
Checking the Base Working Logic for Frequency, Relative Frequency and Cumulative Relative Frequency 
by Creating a New Table - FrequencyTable
"""
frequencyTable = pd.DataFrame(columns=["Unique_Values","Frequency","Relative_Frequency","CumSum"])
frequencyTable

In [ ]:
total = len(dataset)
total

In [ ]:
"""
Checking the Base Working Logic for Frequency, Relative Frequency and Cumulative Relative Frequency 
by Creating a New Table - FrequencyTable
"""
frequencyTable["Unique_Values"] = dataset["open"].value_counts().index
frequencyTable["Frequency"] = dataset["open"].value_counts().values
frequencyTable["Relative_Frequency"] = (frequencyTable["Frequency"]/103)
frequencyTable["CumSum"] = frequencyTable["Relative_Frequency"].cumsum() #Calling an Existing Function .cumsum()

frequencyTable

In [ ]:
"""Creating a Function To Automate the Updatation of Frequency, Relative Frequency and Cumulative Relative Frequency 
by Creating a New Table - FrequencyTable """

def frequencyTable(dataset,columnName):
    frequencyTable = pd.DataFrame(columns=["Unique_Values","Frequency","Relative_Frequency","CumSum"])
    frequencyTable["Unique_Values"] = dataset[columnName].value_counts().index
    frequencyTable["Frequency"] = dataset[columnName].value_counts().values
    frequencyTable["Relative_Frequency"] = (frequencyTable["Frequency"]/103)
    frequencyTable["CumSum"] = frequencyTable["Relative_Frequency"].cumsum() #Calling an Existing Function .cumsum()
    return frequencyTable

In [ ]:
frequencyTable(dataset,columnName)

### Skewness

In [ ]:
""" 
Purpose: It gives Peak of the Graph which May Equal to 3, Lesser than 3 Or Greater than 3. Each Level Indicates below categories
1.Platykurtic <3 , 2.Mesokurtic =3 , 3.Leptokurtic >3 
Adding this Skew and Kurtosis to Function - Univariate which present in the Class - Univariate
"""
dataset.skew()

In [ ]:
Univariate(dataset,quan)